name: Create and Push Tag

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Enter the version number'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: Create tag
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: |
          if [[ ${{ github.event.inputs.version_bump }} != "" ]]; then
            echo ${{ github.event.inputs.version_bump }}
          	git tag ${{ github.event.inputs.version_bump }}; \
            git push origin ${{ github.event.inputs.version_bump }};
          else
            echo "Informe uma versão válida"
            exit 1
          fi
