name: Gerar Tag

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Informe o número da versão'
        required: true
        default: '5.'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar versão bump
        run: |
          if [[ ${{ github.event.inputs.version_bump }} != "" || ${{ github.event.inputs.version_bump }} == "minor" || ${{ github.event.inputs.version_bump }} == "Patch" ]]; then
            echo "Opção válida selecionada."
            echo ${{ github.event.inputs.version_bump }}
          else
            echo "Informe uma versão válida"
            exit 1
          fi
