name: Create and Push Tag

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Enter the version number'
        required: true
env:
  TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: Create tag
        run: |
          echo ${{ github.event.inputs.version_bump }}
          git tag ${{ github.event.inputs.version_bump }}; \

      - name: Push tag
        run: |
          git push origin ${{ github.event.inputs.version_bump }};
