name: Gerar Tag

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Informe o número da versão'
        required: true
        default: '5.'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar versão bump
        run: |
          if [[ ${{ github.event.inputs.version_bump }} != "" ]]; then
            echo ${{ github.event.inputs.version_bump }}
          	git tag ${{ github.event.inputs.version_bump }}; \
            git push origin ${{ github.event.inputs.version_bump }};
          else
            echo "Informe uma versão válida"
            exit 1
          fi
