name: Create and Push Tag

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Enter the version number:'
        required: true
env:
  TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Create tag
        run: |
          CAPTURE_VERSION = "capture-sdk-${{ github.event.inputs.version_bump }}";
          echo "CAPTURE_VERSION=${CAPTURE_VERSION}";
          git tag ${CAPTURE_VERSION}; \
          echo "Tag created successfully"

      - name: Push tag
        run: |
          git push origin ${CAPTURE_VERSION};;
          echo "Tag pushed successfully"
